$ANSIBLE_VAULT;1.1;AES256
62313533623436363965633332356663653737613835653237636333363232613835633030353262
3932633866326432306135643135393933646432636138610a633331386639313639306330613637
61616439326266313462666332383430616161663961346131303835636464386632626562323739
6562613033316438350a663532336464326563376433366631613836306139313733313437343435
65373136336532373963303338643732366361356333633734653935653336313361666362653232
65313936393063643265313365636436343963653034343864643737653636386439623365633433
39396466383532386533356631663561616463366530363832316166633039346537333666376664
30303533383961346238633162613463373430376262373866616335323237396164363264643866
35376632613062323437353464376366306163663832316635653937356161306563383862646437
30363833316330666562336435356364333335343034313463303537326461313336363037623136
64346336306631333461343537663738366262326138316635653538343836303634346165636630
36343761316365643634613839316661613033336339636566656366653135303133646262643937
33623662623831336335316664616435353331313438656439366466316533376463656437386438
61393964373234633865393731333562373531386430313932313133303534313730303333383036
36396133303533643135643136316639353435663362626239313361316434336666333564623462
39386435323864376339353965313364386365653039633563393232333133333235363832376333
37376463333737346535663034373433366436643463396138336362336533303861323763626536
64613735303139303134633836383466376138343663616436393435643833646433386663323530
39383037653437316131623661306662383663356432383562633535626432343964363638613534
36373830363030613839653262346231303236646664396265623238336261623235386163376136
62303837333638346633336462363831656233613938666261303233343339306138363535356661
32646635663834316466363233313433303566313630336464353230396666353534353035313161
31636663343036623463643765383865656463393166343631633531653433636130393562636161
36613237656461373163346439333931633761653039383334643933643030343638343264336266
3965
