$ANSIBLE_VAULT;1.1;AES256
66396331616663386432643032333137626533396663656235626139633439616435303137663566
3561373066333735663331323634373162303638616134620a386134303461343930333930663934
31613361306563643061353538386633393665353636616465663736633964363337333332646563
3065393939626162310a373735303930653631343839353136313335373366323536363966666461
66353764326533663631343636336334643436633434643264303164663233623262323437656465
64366664333035383164653161313833643232616162613434393531306134323461653531323365
31353732356465613539376461396630643233386366613030366231393836653764653964373663
64343761323835376461366463656537356230313730663866343930613031366265653031653539
30613762346433636632343533643962383630333864656334616334313061333837336630306532
3464353130636535653638356531383034636161303665303263
